# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\x12\tassistant\"5\n\x0bUserMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nuser_input\x18\x02 \x01(\t\"/\n\rModelResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x03(\t2S\n\x10\x41ssistantService\x12?\n\x0bSendMessage\x12\x16.assistant.UserMessage\x1a\x18.assistant.ModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMESSAGE']._serialized_start=30
  _globals['_USERMESSAGE']._serialized_end=83
  _globals['_MODELRESPONSE']._serialized_start=85
  _globals['_MODELRESPONSE']._serialized_end=132
  _globals['_ASSISTANTSERVICE']._serialized_start=134
  _globals['_ASSISTANTSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
